version: '3'
services:
  node:
    build:
      context: .
    environment: 
      - BOT_TOKEN=$BOT_TOKEN
    tty: true
    command: yarn run dev
    volumes:
      - .:/app
      -  /app/node_modules